# Generated by Django 5.0.1 on 2024-01-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_fruit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Vegetable',
        ),
    ]
